config/routes.rb
Friendcircle::Application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :circles, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :destroy]

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  attr_accessible :owner_id, :member_ids, :title
  has_many :circle_memberships
  validates :owner_id, :title, presence: true

  has_many :members, through: :circle_memberships, source: :member
  belongs_to :owner,
              class_name: "User",
              foreign_key: :owner_id,
              primary_key: :id

  # accepts_nested_attributes_for :circle_memberships
end

app/models/circle_membership.rb
class CircleMembership < ActiveRecord::Base
  attr_accessible :circle_id, :member_id

  belongs_to :circle
  belongs_to :member, class_name: "User"

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :link#, :post_id
  validates :link,  :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :owner_id, :title, :links_attributes, :circle_ids
  validates :owner_id, presence: true

  has_many :links
  has_many :post_shares
  has_many :circles, through: :post_shares

  accepts_nested_attributes_for :links, :reject_if => :all_blank
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :circle_id, :post_id
  validates :circle_id, :post_id, presence: true

  belongs_to :post
  belongs_to :circle
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :pass_digest, :username, :session_token, :password
  validates :username, :pass_digest, presence: true
  validate :password_length
  has_many :posts,
            :foreign_key => :owner_id,
            :primary_key => :id

  has_many :circles,
    :class_name => "Circle",
    :foreign_key => :owner_id,
    :primary_key => :id

  def reset_session!
    random = SecureRandom.urlsafe_base64
    until User.find_by_session_token(random).nil?
      random = SecureRandom.urlsafe_base64
    end
    self.session_token = random
    self.save!
    random
  end

  def password=(password)
    @password = password
    self.pass_digest = BCrypt::Password.create(@password)
  end

  def password_hash
    BCrypt::Password.new(self.pass_digest)
  end

  private
  def password_length
    errors[:password] << "Password too short" if !@password.nil? &&
                        @password.length < 4
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  def new
    @circle = Circle.new
    @users = User.all
    render :new
  end

  def create
   params[:circle][:owner_id] = current_user.id
    @circle = Circle.new(params[:circle])
    @circle.save!
    redirect_to current_user
  end

  def destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @circles = current_user.circles
    render :new
  end

  def create
    params[:post][:owner_id] = current_user.id
    @post = Post.new(params[:post])
    if @post.save
      redirect_to current_user
    else
      debugger
      @circles = current_user.circles
      render :new
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.password_hash == params[:session][:password]
      flash[:message] = "Welcome back!"
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def new
    @user = User.new
    render :new
  end

  def create
    password = compare_password_and_confirmation(params[:user][:password],
                                              params[:user][:password_confirm])
    @user = User.new(username: params[:user][:username], password: password)
    if @user.save
      login(@user)
      flash[:message] = "User created."
      render :show
      return
    end
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session_token = user.reset_session!
    cookies.permanent[:session_token] = session_token
    current_user = user
  end

  def logout
    current_user.reset_session!
    cookies.delete(:session_token)
    current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(cookies[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def current_user?(user)
    current_user == user
  end


end

app/helpers/users_helper.rb
module UsersHelper
  def compare_password_and_confirmation(pass, conf)
    if pass == conf
      return pass
    else
      flash.now[:message] = "Password and Confirmation do not match"
    end
    nil
  end
end

app/views/circles/new.html.erb
<h2> Create a circle </h2>

<form action= "<%=circles_url%>" method = "post">
  <input type= "text" name="circle[title]" id="circle_table">
  <label for="circle_table"> Circle title </label>
  <br>
  <input type= "hidden" name = "authenticity_token"
  value= "<%= form_authenticity_token%>" >
  <% @users.each do |user| %>
  <label for="item<%=user.id%>"><%= user.username %></label>
  <input type="checkbox" name="circle[member_ids][]"
  value ="<%=user.id%>" id="item<%=user.id%>">
  <br>
  <% end %>
  <input type= "submit", "Give me friends">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendCircle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if logged_in? %>
    <%=button_to 'Log out', session_url, method: 'delete'%>
  <% end %>
<p><%= flash[:message] %></p>
<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h2> Create a Post </h2>

<form action= "<%=posts_url%>" method = "post">
  <input type= "text" name="post[title]" id="title_table" value="<%=@post.title%>">
  <label for="title_table"> Post title </label>
  <br>
  <input type= "text" name="post[body]" id="body_table"
  value="<%=@post.body%>">

  <label for="body_table"> Post content </label>
  <br>
  <input type= "hidden" name = "authenticity_token"
  value= "<%= form_authenticity_token%>" >
  <% @circles.each do |circle| %>
  <label for="item<%=circle.id%>"><%= circle.title %></label>
  <input type="checkbox" name="post[circle_ids][]"
  value ="<%=circle.id%>" id="item<%=circle.id%>">
  <br>
  <% end %>
  <p> Choose circles who can see your post </p>
  <h2>Add up to 3 links</h2>
  <% 3.times do |number| %>
  <input type="text" name="post[links_attributes][<%= number %>][link]">
  <% end %>

  <input type= "submit", "POST!!!">
</form>

app/views/users/new.html.erb
<h2> Sign up for Friends </h2>

<%if @user.errors.any? %>
  <% @user.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= form_for(@user) do |f| %>
<%= f.text_field :username %>
<%= f.label :username %>
<br>
<%= f.password_field :password %>
<%=f.label :password, "Enter password" %>
<br>
<%= f.password_field :password_confirm %>
<%=f.label :password_confirm, "Confirm password"%>
<br>
<%=f.submit "SUBMIT TO ME!"%>
<% end %>

<%= link_to "Already belong?", new_session_url %>

app/views/users/show.html.erb
<%= @user.username %> welcome!
<br>
<br>
<%@user.posts.each do |post| %>
<%=post.title%>
<br>
<%=post.body%>
<br>
<%end%>